--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/sky-min/CommandLib
build-by-default: true
branches:
- master
projects:
  CommandLib:
    path: ""
    model: virion
    type: library
...
